### ISSUE TITLE
Geonames get method

### ISSUE THREAD

**Issue by Torvaney** [ropensci/geonames#19]
It would be great to add support for the geonames `get` API call:

http://www.geonames.org/export/web-services.html#get

Apologies if it's already been done, and I just haven't found it

**Comment by Torvaney** [comment]
Upon further inspection, it seems as though this is because `get` only return XML. Is this correct?

**Comment by sckott** [comment]
@barryrowlingson did you see this yet?

**Comment by barryrowlingson** [comment]
A JSON version of `get` is in the Geonames API:

http://api.geonames.org/getJSON?geonameId=7910950&username=....

You can call this using the unexported low-level geonames package functions:

```
GNget = function(id){geonames:::getJson("getJSON",list(id=as.character(id)))}
GNget(7910950)
```

I could convert that list into a data frame for convenience like I do for every other geonames call but... because the return from `getJSON` is slightly different from every other geonames call I can think of, my data frame conversion functions won't work and I'll have to refactor a few things...

**Comment by Torvaney** [comment]
Thanks, Barry. Seems like it might not be worth the refactoring, then?

I came up with a workaround using the XML API and a few functions from [xml2](https://github.com/r-lib/xml2) - not at the right computer now but I will post it here for posterity when I can.
